#!/bin/sh
# Clean ECMWF data
cleaner -maxfiles 4 '_ecmwf_.*_surface.sqd' /smartmet/data/ecmwf
cleaner -maxfiles 4 '_ecmwf_.*_pressure.sqd' /smartmet/data/ecmwf
cleaner -maxfiles 2 '_ecmwf_.*_surface.sqd' /smartmet/editor/in
cleaner -maxfiles 2 '_ecmwf_.*_pressure.sqd' /smartmet/editor/in

# Clean incoming directory older than 1 day (1 * 24 * 60 = 1440 min)
find /smartmet/data/incoming/ecmwf -mmin +1440 -delete >& /dev/null
