#!/bin/sh
# Clean ICON data
cleaner -maxfiles 4 '_icon_.*_surface.sqd' /smartmet/data/icon
cleaner -maxfiles 4 '_icon_.*_pressure.sqd' /smartmet/data/icon
cleaner -maxfiles 4 '_icon_.*_surface.sqd' /smartmet/editor/in
cleaner -maxfiles 4 '_icon_.*_pressure.sqd' /smartmet/editor/in

# Clean incoming directory older than 1 day (0.5 * 24 * 60 = 720 min)
find /smartmet/data/incoming/icon -mmin +720 -delete >& /dev/null
