#!/bin/sh
# Clean WRF data
cleaner -maxfiles 4 '_wrf_.*_surface.sqd' /smartmet/data/wrf
cleaner -maxfiles 4 '_wrf_.*_pressure.sqd' /smartmet/data/wrf
cleaner -maxfiles 2 '_wrf_.*_surface.sqd' /smartmet/editor/in
cleaner -maxfiles 2 '_wrf_.*_pressure.sqd' /smartmet/editor/in
# Clean incoming directory older than 1 day (1 * 24 * 60 = 1440 min)
find /smartmet/data/incoming/wrf/d01 -mmin +1440 -delete >& /dev/null
find /smartmet/data/incoming/wrf/d02 -mmin +1440 -delete >& /dev/null
