#!/bin/sh
# Clean GSM data
cleaner -maxfiles 4 '_gsm_.*_surface.sqd' %{smartmetroot}/data/gsm
cleaner -maxfiles 4 '_gsm_.*_pressure.sqd' %{smartmetroot}/data/gsm
cleaner -maxfiles 2 '_gsm_.*_surface.sqd' %{smartmetroot}/editor/in
cleaner -maxfiles 2 '_gsm_.*_pressure.sqd' %{smartmetroot}/editor/in
