name: Build RPM Packages

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-rpms:
    name: Build RPM on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['rocky8', 'rocky9']
        include:
          - os: rocky8
            tag: '8'
          - os: rocky9
            tag: '9'
    
    container:
      image: rockylinux:${{ matrix.tag }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install build dependencies
        run: |
          dnf -y install \
            rpm-build \
            rpmdevtools \
            gcc \
            make \
            rpm-devel \
            rpmlint \
            tree
            
      - name: Set up RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mkdir -p ~/rpmbuild/SOURCES/smartmet-data-models
          cp ./*.spec ~/rpmbuild/SPECS/
          cp -r ./* ~/rpmbuild/SOURCES/smartmet-data-models
          
      - name: Build RPM package
        run: |
          cd ~/rpmbuild/SPECS
          rpmbuild -ba *.spec
          
      - name: List generated RPMs
        run: |
          tree ~/rpmbuild/RPMS/
          tree ~/rpmbuild/SRPMS/
          
      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpms-${{ matrix.os }}
          path: |
            ~/rpmbuild/RPMS/
            ~/rpmbuild/SRPMS/
          retention-days: 7

  create-release:
    needs: build-rpms
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true
